- hosts: all
  become: yes
  tasks:
    - name: Install networking utilities
      apt:
        name:
          - vim
          - net-tools
        state: present
    - name: Configure static IP (example for one node)
      copy:
        dest: /etc/network/interfaces
        content: |
          auto eth0
          iface eth0 inet static
              address 192.168.1.10
              netmask 255.255.255.0
              network 192.168.1.0
              gateway 192.168.1.1
      when: inventory_hostname == 'master-node'
